export const NOTIFICATION_GET_START = "NOTIFICATION_GET_START";
export const NOTIFICATION_GET_SUCCESS = "NOTIFICATION_GET_SUCCESS";
export const NOTIFICATION_GET_ERROR = "NOTIFICATION_GET_ERROR";

export const NOTIFICATION_MARK_START = "NOTIFICATION_MARK_START";
export const NOTIFICATION_MARK_SUCCESS = "NOTIFICATION_MARK_SUCCESS";
export const NOTIFICATION_MARK_ERROR = "NOTIFICATION_MARK_ERROR";

export const ON_NOTIFICATION_REQUEST_ADD = "ON_NOTIFICATION_REQUEST_ADD";
export const ON_ACCEPT_REQUEST_ADD = "ON_ACCEPT_REQUEST_ADD";
export const ON_REMOVE_REQUEST_ADD = "ON_REMOVE_REQUEST_ADD";
export const ON_REMOVE_REQUEST_SENT_ADD = "ON_REMOVE_REQUEST_SENT_ADD";
export const ON_REMOVE_NOTIFICATION = "ON_REMOVE_NOTIFICATION";
export const ON_NOTIFICATION_UNLIKE = "ON_NOTIFICATION_UNLIKE";

